sudo: false
dist: focal
language: python
python:
  - 3.6
  - 3.8

install:
  - pip install tox tox-travis
  - sudo apt update
  - sudo apt install -y libgirepository1.0-dev libnm0 python3-gi

script:
  - tox
